/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madgaze_madmagcalibrate_MainActivity */

#ifndef _Included_com_madgaze_madmagcalibrate_MainActivity
#define _Included_com_madgaze_madmagcalibrate_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_madgaze_madmagcalibrate_MainActivity_INIT
#define com_madgaze_madmagcalibrate_MainActivity_INIT 0L
#undef com_madgaze_madmagcalibrate_MainActivity_RECORDING
#define com_madgaze_madmagcalibrate_MainActivity_RECORDING 1L
#undef com_madgaze_madmagcalibrate_MainActivity_STOPPED
#define com_madgaze_madmagcalibrate_MainActivity_STOPPED 2L
/*
 * Class:     com_madgaze_madmagcalibrate_MainActivity
 * Method:    addSample
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_madgaze_madmagcalibrate_MainActivity_addSample
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_madgaze_madmagcalibrate_MainActivity
 * Method:    getParams
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_madgaze_madmagcalibrate_MainActivity_getParams
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_madgaze_madmagcalibrate_MainActivity
 * Method:    setBias
 * Signature: ([D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_madgaze_madmagcalibrate_MainActivity_setBias
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
